name: Build Software
on: 
  push:
    paths-ignore:
      - 'report/**'
      - 'README.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - 'report/**'
      - 'README.md'
      - 'LICENSE'
jobs:
  windows:
    name: Build on Windows
    runs-on: windows-latest
    strategy:
      matrix:
        qt_arch: [win64_msvc2017_64, win32_msvc2017]
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.0.0
        with:
          arch: ${{ matrix.qt_arch }}
          modules: qtcharts
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: build-msvc-x64
        if: contains(matrix.qt_arch,'msvc') && contains(matrix.qt_arch,'win64')
        shell: cmd
        run: |
          cd DIP-src
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          qmake
          nmake
          windeployqt ../bin/
      - name: build-msvc-x86
        if: contains(matrix.qt_arch,'msvc') && contains(matrix.qt_arch,'win32')
        shell: cmd
        run: |
          cd DIP-src
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
          qmake
          nmake
          windeployqt ../bin/
  macos:
    name: Build on MacOS
    runs-on: macos-latest
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.0.0
        with:
          modules: qtcharts
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: build macos
        run: |
          cd DIP-src
          export PATH=$PATH:$Qt5_Dir
          qmake
          make
          macdeployqt ../bin/DIP.app -verbose=1 -dmg
  ubuntu:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.0.0
        with:
          modules: qtcharts
      - name: ubuntu install GL library
        run: sudo apt-get install -y libglew-dev libglfw3-dev
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: build ubuntu
        run: |
          cd DIP-src
          export PATH=$PATH:$Qt5_Dir
          qmake
          make