name: Build on MacOS
on: 
  push:
    paths-ignore:
      - 'report/**'
      - 'README.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - 'report/**'
      - 'README.md'
      - 'LICENSE'
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.0.0
        with:
          modules: qtcharts
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: build macos
        run: |
          cd DIP-src
          export PATH=$PATH:$Qt5_Dir
          qmake
          make
      - name: Upload bin
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: actions/upload-artifact@v1
        with:
          name: DIP-${{ matrix.os }}
          path: bin
