name: Build Report Document

on: 
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@master
      with:
          root_file: report.tex
          working_directory: report
          args: -xelatex
          extra_system_packages: "py-pygments"
    - name: Copy document
      if: startsWith(github.event.ref, 'refs/tags/')
      run: |
        cd report
        mkdir report
        cp out/report.pdf report/report.pdf
    - name: Upload document
      if: startsWith(github.event.ref, 'refs/tags/')
      uses: actions/upload-artifact@v1
      with:
        name: report
        path: report/report
    
