name: Build on Ubuntu
# Qt官方没有linux平台的x86包
on: 
  push:
    paths-ignore:
      - 'report/**'
      - 'README.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - 'report/**'
      - 'README.md'
      - 'LICENSE'
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04,ubuntu-18.04]
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.0.0
        with:
          modules: qtcharts
      - name: ubuntu install GL library
        run: sudo apt-get install -y libglew-dev libglfw3-dev
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: build ubuntu
        run: |
          cd DIP-src
          export PATH=$PATH:$Qt5_Dir
          qmake
          make
      - name: Upload bin
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: actions/upload-artifact@v1
        with:
          name: DIP-${{ matrix.os }}
          path: bin
