name: Build on Windows
on: 
  push:
    paths-ignore:
      - 'report/**'
      - 'README.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - 'report/**'
      - 'README.md'
      - 'LICENSE'
jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        qt_arch: [win64_msvc2017_64, win32_msvc2017]
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.0.0
        with:
          arch: ${{ matrix.qt_arch }}
          modules: qtcharts
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: build-msvc-x64
        if: contains(matrix.qt_arch,'msvc') && contains(matrix.qt_arch,'win64')
        shell: cmd
        run: |
          cd DIP-src
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          qmake
          nmake
      - name: build-msvc-x86
        if: contains(matrix.qt_arch,'msvc') && contains(matrix.qt_arch,'win32')
        shell: cmd
        run: |
          cd DIP-src
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
          qmake
          nmake
